services:
  - type: web
    name: nvn-india-portal
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT server:app
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
